spring:
  datasource:
    username: postgres
    password: 1234    
    url: jdbc:postgresql://localhost:5432/school    
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 5
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
  thymeleaf:
    cache=false
    enabled=true
    prefix=classpath:/templates/
    suffix=.html
    name=Bootstrap
    
logging:
  level:
    org.springframework.security: debug